language: objective-c
osx_image: xcode10.1
before_install: brew update
podfile: someapp/Podfile
xcode_workspace: someapp/someapp.xcworkspace
xcode_scheme: someapp
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone 8
